# Generated by Django 3.0.4 on 2020-03-31 19:18

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='blog/images/')),
                ('caption', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
